// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/25/2025, 2:55:33 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/DHPI DMC 93/Documents/GitHub/Resume/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DHPI DMC 93/Documents/GitHub/Resume/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DHPI DMC 93/Documents/GitHub/Resume/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DHPI DMC 93/Documents/GitHub/Resume/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DHPI DMC 93/Documents/GitHub/Resume/app/plugins/**/*.{js,ts,mjs}","C:/Users/DHPI DMC 93/Documents/GitHub/Resume/app/composables/**/*.{js,ts,mjs}","C:/Users/DHPI DMC 93/Documents/GitHub/Resume/app/utils/**/*.{js,ts,mjs}","C:/Users/DHPI DMC 93/Documents/GitHub/Resume/app/pages/index.vue","C:/Users/DHPI DMC 93/Documents/GitHub/Resume/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DHPI DMC 93/Documents/GitHub/Resume/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/DHPI DMC 93/Documents/GitHub/Resume/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;